name: Auto Deploy to Server

on:
  push:
    branches:
      - feature/backend-contractors

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: vh326.timeweb.ru
          username: spugovxsim
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/public_html/v3
            git pull origin feature/backend-contractors
